### ISSUE TITLE
[ Error ] - Unable to install the web server locally

### ISSUE THREAD

**Issue by isasmendiagus** [httptoolkit/httptoolkit.tech#13]
I run `npm install` and after a few seconds I got this error:
Any idea what would be happening?

Thanks

```
10226 timing reify:rollback:retireShallow Completed in 0ms
10227 timing command:install Completed in 63876ms
10228 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
10228 verbose stack     at /home/ubuntu/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:84:17
10228 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
10229 verbose statusCode 401
10230 verbose pkgid @fortawesome/react-fontawesome@https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/react-fontawesome-0.1.4.tgz
10231 verbose cwd /home/ubuntu/Projects/httptoolkit.tech
10232 verbose Linux 5.11.0-41-generic
10233 verbose argv "/home/ubuntu/.nvm/versions/node/v14.17.0/bin/node" "/home/ubuntu/.nvm/versions/node/v14.17.0/bin/npm" "install"
10234 verbose node v14.17.0
10235 verbose npm  v8.1.3
10236 error code E401
10237 error Incorrect or missing password.
10238 error If you were trying to login, change your password, create an
10238 error authentication token or enable two-factor authentication then
10238 error that means you likely typed your password in incorrectly.
10238 error Please try again, or recover your password at:
10238 error     https://www.npmjs.com/forgot
10238 error
10238 error If you were doing some other operation then your saved credentials are
10238 error probably out of date. To correct this please try logging in again with:
10238 error     npm login
10239 verbose exit 1
```

**Comment by pimterry** [comment]
Ah, I think I've seen this elsewhere, something changed in npm 7 or 8 which means that the current lock file URLs cause some problems... Let me check a minute, I think I can probably push a fix pretty quickly.

**Comment by pimterry** [comment]
Now fixed :+1: I'm going to push a couple more dep updates in a minute too, but for now bab252cbd41be0e3e991288c507219d1335cf1aa should sort this issue out for you. Thanks for reporting this!

**Comment by isasmendiagus** [comment]
Hi @pimterry , thank for your fast response!
It's fixed! :smile: 

By the way, nice project! 
Cheers
