### ISSUE TITLE
Can't connect to HTTP ToolKit On Android 9

### ISSUE THREAD

**Issue by trantrongkim98** [httptoolkit/httptoolkit.tech#17]
OS: Samsung Android 9
PC: MacOS BigSur
Log:
```
01-25 11:29:06.106 15860 19702 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 10.0.2.2:8000
01-25 11:29:06.106 15860 19368 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 10.0.3.2:8000
01-25 11:29:06.106 15860 18401 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::aede:48ff:fe00:1122:8000
01-25 11:29:06.106 15860 17779 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::1c43:3d61:14f9:389:8000
01-25 11:29:06.106 15860 19885 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 2001:ee0:53fe:1ce0:10bf:34c8:794e:eac8:8000
01-25 11:29:06.107 15860 18313 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 2001:ee0:53fe:1ce0:8cfa:3da8:ea28:e481:8000
01-25 11:29:06.108 15860 19695 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 192.168.1.22:8000
01-25 11:29:06.109 15860 18401 D NetworkManagementSocketTagger: tagSocket(71) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.109 15860 19368 D NetworkManagementSocketTagger: tagSocket(72) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.109 15860 18313 D NetworkManagementSocketTagger: tagSocket(74) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.109 15860 17779 D NetworkManagementSocketTagger: tagSocket(82) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.110 15860 19702 D NetworkManagementSocketTagger: tagSocket(70) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.110 15860 19695 D NetworkManagementSocketTagger: tagSocket(85) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.111  2743  2743 I display : [PrimaryDisplay] [DYNAMIC_RECOMP] first frame after HWC_2_GLES
01-25 11:29:06.111  2743  2743 I display : [PrimaryDisplay] [DYNAMIC_RECOMP] GLES_2_HWC by high FPS(5)
01-25 11:29:06.111 15860 19885 D NetworkManagementSocketTagger: tagSocket(80) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.111 15860 19887 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::38cb:5ff:feda:e05f:8000
01-25 11:29:06.114 15860 18313 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 2001:ee0:53fe:1ce0:8cfa:3da8:ea28:e481: java.net.ConnectException: Failed to connect to /2001:ee0:53fe:1ce0:8cfa:3da8:ea28:e481:8000
01-25 11:29:06.115 15860 19702 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.2.2: java.net.ConnectException: Failed to connect to /10.0.2.2:8000
01-25 11:29:06.116 15860 19887 D NetworkManagementSocketTagger: tagSocket(69) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.116 15860 19695 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 192.168.1.22: java.net.ConnectException: Failed to connect to /192.168.1.22:8000
01-25 11:29:06.116 15860 17779 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::1c43:3d61:14f9:389: java.net.ConnectException: Failed to connect to /fe80::1c43:3d61:14f9:389:8000
01-25 11:29:06.116 15860 19368 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 10.0.3.2: java.net.ConnectException: Failed to connect to /10.0.3.2:8000
01-25 11:29:06.117 15860 18401 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::aede:48ff:fe00:1122: java.net.ConnectException: Failed to connect to /fe80::aede:48ff:fe00:1122:8000
01-25 11:29:06.118 15860 19698 V tech.httptoolkit.android (kotlinx.coroutines.SupervisorCoroutine): Proxy tests started
01-25 11:29:06.119 15860 19885 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 2001:ee0:53fe:1ce0:10bf:34c8:794e:eac8: java.net.ConnectException: Failed to connect to /2001:ee0:53fe:1ce0:10bf:34c8:794e:eac8:8000
01-25 11:29:06.119 15860 19696 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::7870:8f78:7671:e150:8000
01-25 11:29:06.119 15860 19888 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::38cb:5ff:feda:e05f:8000
01-25 11:29:06.120 15860 19887 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::38cb:5ff:feda:e05f: java.net.ConnectException: Failed to connect to /fe80::38cb:5ff:feda:e05f:8000
01-25 11:29:06.120 15860 19890 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 192.168.57.1:8000
01-25 11:29:06.121 15860 20106 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy fe80::ae8b:c62a:46c0:d5f4:8000
01-25 11:29:06.121 15860 19888 D NetworkManagementSocketTagger: tagSocket(69) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.121 15860 19696 D NetworkManagementSocketTagger: tagSocket(70) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.124 15860 19890 D NetworkManagementSocketTagger: tagSocket(69) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.125 15860 19696 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::7870:8f78:7671:e150: java.net.ConnectException: Failed to connect to /fe80::7870:8f78:7671:e150:8000
01-25 11:29:06.126 15860 20106 D NetworkManagementSocketTagger: tagSocket(70) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.126 15860 19888 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::38cb:5ff:feda:e05f: java.net.ConnectException: Failed to connect to /fe80::38cb:5ff:feda:e05f:8000
01-25 11:29:06.127 15860 19890 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 192.168.57.1: java.net.ConnectException: Failed to connect to /192.168.57.1:8000
01-25 11:29:06.130 15860 20106 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address fe80::ae8b:c62a:46c0:d5f4: java.net.ConnectException: Failed to connect to /fe80::ae8b:c62a:46c0:d5f4:8000
01-25 11:29:06.132 15860 19890 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Testing proxy 127.0.0.1:8000
01-25 11:29:06.134 15860 19890 D NetworkManagementSocketTagger: tagSocket(69) with statsTag=0xffffffff, statsUid=-1
01-25 11:29:06.146  3173  5664 D SamsungAlarmManager: Cancel Alarm calling from uid:10073 pid :4492 / op:PendingIntent{b418d0f: PendingIntentRecord{a424052 com.google.android.gms broadcastIntent}}
01-25 11:29:06.148 15860 19890 I tech.httptoolkit.android (kotlinx.coroutines.UndispatchedCoroutine): Error testing proxy address 127.0.0.1: java.net.SocketException: Connection reset
01-25 11:29:06.149  3173  5664 I SamsungAlarmManager: setLocked to kernel - T:2 / 20220125T113008, SetElapsed=1983446, nowELAPSED=1920896
01-25 11:29:06.149  3173  5664 I SamsungAlarmManager: setLocked to kernel - T:3 / 20220125T113000, SetElapsed=1974747, nowELAPSED=1920896
01-25 11:29:06.149 15860 19890 E tech.httptoolkit.android (kotlinx.coroutines.DispatchedCoroutine): java.net.SocketException: Connection reset
01-25 11:29:06.149 15860 19890 W System.err: java.net.SocketException: Connection reset
01-25 11:29:06.149  3173  5664 D SamsungAlarmManager: setExact Listener (T:2/F:0/AC:false) 20220125T112908 - CU:1000/CP:3173
01-25 11:29:06.149  3173  5664 I SamsungAlarmManager: setLocked to kernel - T:2 / 20220125T112908, SetElapsed=1922749, nowELAPSED=1920897
01-25 11:29:06.149 15860 19890 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
01-25 11:29:06.149 15860 19890 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
01-25 11:29:06.149 15860 19890 W System.err: 	at okio.InputStreamSource.read(Okio.kt:93)
01-25 11:29:06.150 15860 19890 W System.err: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
01-25 11:29:06.150 15860 19890 W System.err: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
01-25 11:29:06.150 15860 19890 W System.err: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
01-25 11:29:06.150 15860 19890 W System.err: 	at okhttp3.RealCall.execute(RealCall.kt:67)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt$request$2.invokeSuspend(ProxySetup.kt:136)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt$request$2.invoke(Unknown Source:10)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt.request(ProxySetup.kt:135)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt$testProxyAddress$2.invokeSuspend(ProxySetup.kt:100)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt$testProxyAddress$2.invoke(Unknown Source:10)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt.testProxyAddress(ProxySetup.kt:86)
01-25 11:29:06.150 15860 19890 W System.err: 	at tech.httptoolkit.android.ProxySetupKt$getProxyConfig$2$1.invokeSuspend(ProxySetup.kt:71)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
01-25 11:29:06.150 15860 19890 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
01-25 11:29:06.151 15860 19890 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
01-25 11:29:06.151 15860 19890 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by pimterry** [comment]
Hi @trantrongkim98! I see you closed this just after opening it, does that mean you fixed it yourself?

If not, from the description here it looks like every IP address for your computer wasn't accessible from your device, and trying to send traffic via the ADB proxy tunnel saw a connection reset. Do you know if any of the IP addresses above should work for your case?

One thing that could cause this is having some kind of rule in your HTTP Toolkit that matches this setup request (a request for `http://android.httptoolkit.tech/config`) and closes the connection. Do you have one of those?
